Ensure div IDs get lowercased (but not class=bc-data divs)
testing/content/files/en-us/learn/css/css_layout/introduction/flex
otherwise fails without this change, with the following error:

> error: MacroLiveSampleError within
> /home/runner/work/yari/yari/testing/content/files/en-us/learn/css/css_layout/introduction/flex/index.html,
> line 20 column 4 (unable to find any live code samples for "flex_1"
> within /en-US/docs/Learn/CSS/CSS_layout/Introduction/Flex)

And we need make sure not to touch the IDs for class=bc-data divs,
because the system does case-sensitive matching on those.